version: '3.7'

services:
    preact:
        build: 
            context: .
            dockerfile: dev.Dockerfile
        environment:
            docker: "true"
        ports:
            - "3000:3000"
        volumes:
            - ./src:/app/src