// This file is automatically generated from your CSS. Any edits will be overwritten.
declare namespace StyleScssNamespace {
    export interface StyleScss {
        bar: string;
        link: string;
        right: string;
    }
}

declare const StyleScssModule: StyleScssNamespace.StyleScss;

export = StyleScssModule;
