// This file is automatically generated from your CSS. Any edits will be overwritten.
declare namespace StyleScssNamespace {
    export interface StyleScss {
        body: string;
        data: string;
        image: string;
        item: string;
    }
}

declare const StyleScssModule: StyleScssNamespace.StyleScss;

export = StyleScssModule;
