name: Docker

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test_docker:
    name: test docker
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
        name: Setup Repo for Docker
      
      - name: Build the DockerProd Image
        run: docker build . --file Dockerfile --tag prod-test:$(date +%s) --rm

      - name: Build the DockerDev Image
        run: docker build . --file dev.Dockerfile --tag prod-test:$(date +%s) --rm